spring.application.name=API gateway
server.port=7080

#Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:7111/eureka/
eureka.instance.hostname=localhost
eureka.instance.virtual-host-name=GATEWAY-SVC

#SKIP DB CONFIGURATION
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.main.web-application-type=reactive

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-svc
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/users/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[0].filters[1]=AuthFilter
spring.cloud.gateway.routes[0].filters[2]=RequestFilter

spring.cloud.gateway.routes[1].id=task-service
spring.cloud.gateway.routes[1].uri=lb://task-svc
spring.cloud.gateway.routes[1].predicates[0]=Path=/tasks/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/tasks/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[1].filters[1]=AuthFilter
spring.cloud.gateway.routes[1].filters[2]=RequestFilter

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=lb://auth-svc
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/auth/(?<segment>.*), /${segment}
spring.cloud.gateway.routes[2].filters[1]=RequestFilter